server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        format_sql: true
  h2:
    console:
      enabled: on


datasource:
  velog:
    graphql:
      url: https://v2cdn.velog.io/graphql
      batch:
        size:
          max: 32
      user:
        tag:
          size:
            max: 3

view:
  file-path:
    background:
    made-image:
  font:

encryption:
  secret-key: ${ENCRYPTION_KEY}
